### ISSUE TITLE
Channel not found

### ISSUE THREAD

**Issue by vaggelis2018** [aznamier/keycloak-event-listener-rabbitmq#11]
Hello I am using the latest version of keycloak-event-listener and I get the following error.
```
keycloak-to-rabbitmq ERROR sending message: KK.EVENT.ADMIN.demoscope.SUCCESS.CLIENT.UPDATE
keycloak_1   | 09:01:52,367 ERROR [stderr] (default task-16) com.rabbitmq.client.AlreadyClosedException: channel is already closed due to channel error; protocol method: #method<channel.close>(reply-code=404, reply-text=NOT_FOUND - no exchange 'registrations' in vhost '/', class-id=60, method-id=40)
```

Is there any way to create the channel when starting the process with docker-compose. I tried to find a way to create the channel with the rabbitmq image but with no luck.

Thanks in advance.

**Comment by aznamier** [comment]
That looks like your configuration of Keycloak is trying to send messages to exchange: `registrations` but that does not exist on your Rabbit. Could you check that, and maybe share your current plugin configuration?

**Comment by vaggelis2018** [comment]
@aznamier Yeap this is actually my problem. I want to create the channel when starting keycloak. I tried to find a way to create it from rabbitmq configuration and I had no luck with it.
