### ISSUE TITLE
SSL protocol support

### ISSUE THREAD

**Issue by pyaroshik** [aznamier/keycloak-event-listener-rabbitmq#13]
Current implementation doesn't allow to establish a connection over TLS.

**Comment by aznamier** [comment]
Hi, 

From a quick glance it would hopefully be a one-liner to add support for TLS **without peer verification** as per this: https://www.rabbitmq.com/ssl.html#java-client-connecting

We could make that so it can be driven from the env variable setting.

Would that help with your issue? I don't have a RabbitMq TLS installation to test it at hand, @pyaroshik are you able to help with testing that, or maybe even contributing the fix?

Btw: the second option to fully support TLS with peer verification, that has a lots of dependencies which could be quite a challenge to fit into configurable plugin.

**Comment by pyaroshik** [comment]
Hi, yeah sure, 'factory.useSslProtocol();' will be enough with appropriate env switcher. I will provide a PR a bit later.

**Comment by aznamier** [comment]
@pyaroshik Thank you for this valuable enhancement. It is now in 2.1
