### ISSUE TITLE
User CREATE event

### ISSUE THREAD

**Issue by hound672** [aznamier/keycloak-event-listener-rabbitmq#18]
Hello.
Can I receive event with type USER.CREATE.
I see this event type on ```Admin events``` page.
The event emits when I login with new user via github, google etc.

**Comment by aznamier** [comment]
Hello, this plugin doesn't filter any events. Everything that Keycloak publishes to its evens (logs, Admin events and client events) are also published into the Rabbit.

I have just tested USER.CREATE event on my installation and its being sent.

<img width="988" alt="Screen Shot 2022-01-12 at 00 56 31" src="https://user-images.githubusercontent.com/4445230/149045021-9ee2d7d5-c3c3-4b17-9f60-00f6318315eb.png">
