### ISSUE TITLE
[Discussion] Keycloak 17.0.0 support?

### ISSUE THREAD

**Issue by armujahid** [aznamier/keycloak-event-listener-rabbitmq#19]
Keycloak 17.0.0 has been released with breaking changes. They switched from WildFly to Quarkus. 
https://www.keycloak.org/2022/02/keycloak-1700-released.html
I hope that this plugin/provider is still compatible. 
Otherwise we will have to migrate it as mentioned in their migration guide.
https://www.keycloak.org/migration/migrating-to-quarkus
![image](https://user-images.githubusercontent.com/3725386/155661482-105076ba-3bb8-4987-a83f-f134c900dab8.png)

**Comment by aznamier** [comment]
My initial thoughts are that it should be compatible with the environment variable configuration. @armujahid are you able to test it out?

**Comment by armujahid** [comment]
I will test it and will let you know.

**Comment by armujahid** [comment]
This is working fine with v17.0.0
Just usage steps are different so may be we should update readme and add new section for `>v17.0.0`
Providers directory is now `/opt/keycloak/providers/`
My dockerfile looks like this:
I am using multiple providers located in `./bin` that's why I am copying all providers in builder stage.
```
FROM quay.io/keycloak/keycloak:17.0.0 as builder

ENV KC_DB=mysql
COPY ./bin /opt/keycloak/providers/
RUN /opt/keycloak/bin/kc.sh build


FROM quay.io/keycloak/keycloak:17.0.0
COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
COPY --from=builder /opt/keycloak/providers/ /opt/keycloak/providers/

WORKDIR /opt/keycloak
ENV KC_HOSTNAME_STRICT=false
ENV KC_HTTP_ENABLED=true

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
```

**Comment by aznamier** [comment]
Awesome. Thanks for checking that out @armujahid
