### ISSUE TITLE
Documentation for keycloak 17+

### ISSUE THREAD

**Issue by durop** [aznamier/keycloak-event-listener-rabbitmq#24]
Hi, the path of the plugin for Keycloak version 17 and newer is now `/opt/keycloak/providers/keycloak-to-rabbit-3.0.jar`.

## USAGE:
1. [Download the latest jar](https://github.com/aznamier/keycloak-event-listener-rabbitmq/blob/target/keycloak-to-rabbit-3.0.jar?raw=true) or build from source: ``mvn clean install``
2. Copy jar into your Keycloak 
    1. Keycloak version 17+ `/opt/keycloak/providers/keycloak-to-rabbit-3.0.jar` 
    2. Keycloak version 16 and older `/opt/jboss/keycloak/standalone/deployments/keycloak-to-rabbit-3.0.jar`
3. Configure as described below (option 1 or 2 or 3)
4. Restart the Keycloak server
5. Enable logging in Keycloak UI by adding **keycloak-to-rabbitmq**  
 `Manage > Events > Config > Events Config > Event Listeners`

**Comment by diegosiao** [comment]
Hi! Where do we find a complete list of valid KK.EVENT.ADMIN.<realm>.SUCCESS.*** events to bind to?

**Comment by aznamier** [comment]
@durop Thank you, I have now updated the documentation as you suggested.
