### ISSUE TITLE
Persistent RabbitMQ channel

### ISSUE THREAD

**Issue by ath88** [aznamier/keycloak-event-listener-rabbitmq#3]
From my experience using RabbitMQ, it is recommended to keep a single open channel instead of connecting and disconnecting regularly. 

Would you be open for such a change?

**Comment by aznamier** [comment]
Originally I thought that creating a connection for each message is an easy self healing mechanics in case something goes wrong with the Rabbit Server and connection dies. It seemed like less of the devil, as opposed to eg. restarting Keycloak server to resume the broken connection. Do you experience performance issues?

**Comment by aznamier** [comment]
Closing it as there is no more activity on this topic
