### ISSUE TITLE
LDAP user creation event

### ISSUE THREAD

**Issue by diegosiao** [aznamier/keycloak-event-listener-rabbitmq#53]
Is it possible to handle an event when an LDAP user is created on Keycloak? 

Apparently, when an user is imported into Keycloak no event is created whatsoever. Is that by design or that's an unexpected behavior? 

Keycloak version: 15.0.2
Plugin v3.0.1

**Comment by aznamier** [comment]
@diegosiao That would be a question to a Keycloak project forum. The rabbit listener (as any other listener) reacts to events handled by Keycloak which are configurable in Keycloak events page.
